# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@anthropic-ai/sandbox-runtime-0.0.13" = {
      name = "_at_anthropic-ai_slash_sandbox-runtime";
      packageName = "@anthropic-ai/sandbox-runtime";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@anthropic-ai/sandbox-runtime/-/sandbox-runtime-0.0.13.tgz";
        sha512 = "rjjmp3MVDn3Yl4ywNVM2Dr7+Q/KzsvsmLl8prP10Mi/+3F3Gs997UiFx3WXqESJtnYkznOuYUp0VhFDfOyJFPw==";
      };
    };
    "@pondwader/socks5-server-1.0.10" = {
      name = "_at_pondwader_slash_socks5-server";
      packageName = "@pondwader/socks5-server";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pondwader/socks5-server/-/socks5-server-1.0.10.tgz";
        sha512 = "bQY06wzzR8D2+vVCUoBsr5QS2U6UgPUQRmErNwtsuI6vLcyRKkafjkr3KxbtGFf9aBBIV2mcvlsKD1UYaIV+sg==";
      };
    };
    "@types/lodash-4.17.20" = {
      name = "_at_types_slash_lodash";
      packageName = "@types/lodash";
      version = "4.17.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/lodash/-/lodash-4.17.20.tgz";
        sha512 = "H3MHACvFUEiujabxhaI/ImO6gUrd8oOurg7LQtS7mbwIXA/cUqWrvBsaeJ23aZEPk1TAYkurjfMbSELfoCXlGA==";
      };
    };
    "@types/lodash-es-4.17.12" = {
      name = "_at_types_slash_lodash-es";
      packageName = "@types/lodash-es";
      version = "4.17.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/lodash-es/-/lodash-es-4.17.12.tgz";
        sha512 = "0NgftHUcV4v34VhXm8QBSftKVXtbkBG3ViCjs6+eJ5a6y6Mi/jiFGPc1sC7QK+9BFhWrURE3EOggmWaSxL9OzQ==";
      };
    };
    "commander-12.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-12.1.0.tgz";
        sha512 = "Vw8qHK3bZM9y/P10u3Vib8o/DdkvA2OtPtZvD871QKjy74Wj1WSKFILMPRPSdUSx5RFK1arlJzEtA4PkFgnbuA==";
      };
    };
    "lodash-es-4.17.21" = {
      name = "lodash-es";
      packageName = "lodash-es";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.21.tgz";
        sha512 = "mKnC+QJ9pWVzv+C4/U3rRsHapFfHvQFoFB92e52xeyGMcX6/OlIl78je1u8vePzYZSkkogMPJ2yjxxsb89cxyw==";
      };
    };
    "shell-quote-1.8.3" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "1.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.8.3.tgz";
        sha512 = "ObmnIF4hXNg1BqhnHmgbDETF8dLPCggZWBjkQfhZpbszZnYur5DUljTcCHii5LC3J5E0yeO/1LIMyH+UvHQgyw==";
      };
    };
    "zod-3.25.76" = {
      name = "zod";
      packageName = "zod";
      version = "3.25.76";
      src = fetchurl {
        url = "https://registry.npmjs.org/zod/-/zod-3.25.76.tgz";
        sha512 = "gzUt/qt81nXsFGKIFcC3YnfEAx5NkunCfnDlvuBSSFS02bcXu4Lmea0AFIUwbLWxWPx3d9p8S5QoaujKcNQxcQ==";
      };
    };
  };
  args = {
    name = "global-node-packages";
    packageName = "global-node-packages";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@anthropic-ai/sandbox-runtime-0.0.13"
      sources."@pondwader/socks5-server-1.0.10"
      sources."@types/lodash-4.17.20"
      sources."@types/lodash-es-4.17.12"
      sources."commander-12.1.0"
      sources."lodash-es-4.17.21"
      sources."shell-quote-1.8.3"
      sources."zod-3.25.76"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Global Node.js packages managed by Nix";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
